### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by shawnlimws** [shawnlimws/wdi-sg-playground#1]
@cbas Hi Seb! Let me know what you think! :)

**Comment by sebdeckers** [comment]
Great!

Feedback:
- Would be good to make the dialog shrink on smaller displays. Try using the Device Mode settings in Chrome's Developer Tools to test the code in various screen sizes. Perhaps use the `max-width` property  to avoid elements going off-screen.
- `flex-direction: column;` should be set on an element with `display: flex;` otherwise it won't do anything.
- Avoid overriding a previously set property in the same CSS rule. Use the 2 or 4 value syntax.
  
  ```
  margin: auto;
  margin-top: 100px;
  /* should just be: */
  margin: 100px auto auto auto;
  ```
- Try vertically centering the dialog using flexbox. Look at the `justify-content` and `align-items` properties.

**Comment by shawnlimws** [comment]
Okay! Will try to make the amendments. Thanks! :)
